// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbirqilwmqupcqjvekkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiaXJxaWx3bXF1cGNxanZla2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjY1MzAsImV4cCI6MjA2MTQ0MjUzMH0.7c8jwvC_0V9-ZzuWJEcsc82YiUijFxOhrcab_DFk_7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);